spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ENC(ZXLfMoRvUqqfxb9TjemdWIq8AIZQ7iIhhI1GBI43AcvTJHOcSPQYjlytdU688gl4KQg+HrRNZiU=)
    username: ENC(/qRPiX/qFCQLKqOAduNI5VcqQtGsUyWDoLGCRRCYwbw=)
    password: ENC(yPuP4hpCPGJMfyimsgPmrcwW0leC7fKn8FF7w6TqZIk=)
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
server:
#  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 18000
      cookie:
        max-age: 18000
        name: PENNY_PILOT_JSESSIONID
#logging:
#  config: classpath:log4j2.yml
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
springdoc:
  api-docs:
    enabled: true
#    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /index.html
    groups-order: ASC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    display-request-duration: true
    disable-swagger-default-url: true
